version: '3.8'

services:
 db:
  image: mysql:latest
  container_name: my_custom_mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 'admin'
  ports:
   - "127.0.0.1:3306:3306"
  volumes:
   - my-db:/var/lib/mysql

 app:
  build:
   context: ./GymAiBackend
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  depends_on:
   - db
  volumes:
   - ./GymAi:/app

volumes:
 my-db:
  driver: local
